# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/JayMadden/game_starter 2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/JayMadden/game_starter 2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/JayMadden/game_starter 2/CMakeFiles" "/Users/JayMadden/game_starter 2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/JayMadden/game_starter 2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameStarter

# Build rule for target.
GameStarter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameStarter
.PHONY : GameStarter

# fast build rule for target.
GameStarter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/build
.PHONY : GameStarter/fast

game/src/Engine.o: game/src/Engine.cpp.o

.PHONY : game/src/Engine.o

# target to build an object file
game/src/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Engine.cpp.o
.PHONY : game/src/Engine.cpp.o

game/src/Engine.i: game/src/Engine.cpp.i

.PHONY : game/src/Engine.i

# target to preprocess a source file
game/src/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Engine.cpp.i
.PHONY : game/src/Engine.cpp.i

game/src/Engine.s: game/src/Engine.cpp.s

.PHONY : game/src/Engine.s

# target to generate assembly for a file
game/src/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Engine.cpp.s
.PHONY : game/src/Engine.cpp.s

game/src/GameObject.o: game/src/GameObject.cpp.o

.PHONY : game/src/GameObject.o

# target to build an object file
game/src/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/GameObject.cpp.o
.PHONY : game/src/GameObject.cpp.o

game/src/GameObject.i: game/src/GameObject.cpp.i

.PHONY : game/src/GameObject.i

# target to preprocess a source file
game/src/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/GameObject.cpp.i
.PHONY : game/src/GameObject.cpp.i

game/src/GameObject.s: game/src/GameObject.cpp.s

.PHONY : game/src/GameObject.s

# target to generate assembly for a file
game/src/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/GameObject.cpp.s
.PHONY : game/src/GameObject.cpp.s

game/src/Ship.o: game/src/Ship.cpp.o

.PHONY : game/src/Ship.o

# target to build an object file
game/src/Ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Ship.cpp.o
.PHONY : game/src/Ship.cpp.o

game/src/Ship.i: game/src/Ship.cpp.i

.PHONY : game/src/Ship.i

# target to preprocess a source file
game/src/Ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Ship.cpp.i
.PHONY : game/src/Ship.cpp.i

game/src/Ship.s: game/src/Ship.cpp.s

.PHONY : game/src/Ship.s

# target to generate assembly for a file
game/src/Ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/Ship.cpp.s
.PHONY : game/src/Ship.cpp.s

game/src/main.o: game/src/main.cpp.o

.PHONY : game/src/main.o

# target to build an object file
game/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/main.cpp.o
.PHONY : game/src/main.cpp.o

game/src/main.i: game/src/main.cpp.i

.PHONY : game/src/main.i

# target to preprocess a source file
game/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/main.cpp.i
.PHONY : game/src/main.cpp.i

game/src/main.s: game/src/main.cpp.s

.PHONY : game/src/main.s

# target to generate assembly for a file
game/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameStarter.dir/build.make CMakeFiles/GameStarter.dir/game/src/main.cpp.s
.PHONY : game/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GameStarter"
	@echo "... game/src/Engine.o"
	@echo "... game/src/Engine.i"
	@echo "... game/src/Engine.s"
	@echo "... game/src/GameObject.o"
	@echo "... game/src/GameObject.i"
	@echo "... game/src/GameObject.s"
	@echo "... game/src/Ship.o"
	@echo "... game/src/Ship.i"
	@echo "... game/src/Ship.s"
	@echo "... game/src/main.o"
	@echo "... game/src/main.i"
	@echo "... game/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

